### ISSUE TITLE
Any recommendation on setting screen size (absolute x,y) after initialization?

### ISSUE THREAD

**Issue by wade-welles** [bendahl/uinput#10]
Such as when the resolution of the screen changes and the touch pad needs to be updated to fit the new size?

**Comment by bendahl** [comment]
Hi Wade!

Interesting use case... I hadn't considered this. Off the top of my head I'm not aware of any such possibility, but I will investigate that. However, even if this shouldn't be possible, one thing that is possible is to create two separate devices - one for each layout. I've added a test in touchpad_test.go that verifies this. So the basic idea would be to use one "horizontal touch pad" and one "vertical touch pad", switching devices every time the device orientation changes. This wouldn't require any sort of (re-)initialization at runtime.

Anyhow, I will take a closer look at this to see whether there is any chance of changing the size of a device once it's been created.

Cheers,
Ben

**Comment by bendahl** [comment]
Another thought just popped into my mind: Regardless of how this can or cannot be handled on the driver level I do believe that for your use case it would be beneficial to have a function like "FlipOrientation()" to switch between horizontal and vertical screen orientation. This would then allow to nicely encapsulate whatever needs to be done in order to change the screen size. Would this help?

**Comment by bendahl** [comment]
Hey Wade,

any update on this? Have you tried any of the suggested solutions? Do you need further assistance? Let me know.

Cheers,
Ben

**Comment by bendahl** [comment]
Hi Wade,

did you try the suggested approach? Did this work for you? Since I haven't heard anything back so far, I'm assuming that you've been able to resolve this. If not, please let me know, so we can find a solution that works for you.

Since the problem you described can be solved, I will close this ticket in case I don't hear back from you in the next couple of days. In case you still need more input let me know and reopen the issue if need be.

Cheers,
Ben

**Comment by bendahl** [comment]
Hi Wade,

I'm assuming that my suggestions did help, since I haven't heard back. Therefore i will close this issue. If there should be any remaining problems that you need help with or further questions, feel free to contact me or open up another issue.

Cheers,
Ben
