### ISSUE TITLE
Keyboard issue on PrimeOS

### ISSUE THREAD

**Issue by spxvszero** [bendahl/uinput#24]
Hi, I am working on PrimeOS which based on  android x86. Using the stable v1 uinput.v1 version. It works nice while using mouse input. 

But there is an issue when using keyboard input. Calling on `keyboard.KeyPress` only works on kernel but not application.

according to [Android Source Site](https://source.android.com/devices/input#input-pipeline), Once i thought maybe something wrong with HID so that application could capture the input from virtual device.

After read a lot about linux drivers and some research, i got wrong way again....

Finially, i try to modify this code in `keyboard.go` file

https://github.com/bendahl/uinput/blob/baaf192f1b6996b15ee151cfee2d0879ab561b96/keyboard.go#L105

change `keyMax` to `249`, the number is the biggest number defined in `keycodes.go`.

It works.

I think maybe `keyMax` define too big (0x2ff), and cover some code in some system.

Hope this will help some people.

Thanks.

**Comment by bendahl** [comment]
Hi there,

thanks for the detailed problem report! 

This seems like an interesting issue. I haven't encountered this so far. However, technically the keyboard won't use any keys > 248 anyway. The reason why a value this high is currently used in uinput/keycodes.go is that the max value defined in input-event-codes.h on an x86_64 machine (Kernel 5.8) is currently defined as 0x2ff. Since it's not necessary to set a limit that high for a regular keyboard, I would rather ensure maximum compatibility between systems rather than enabling keycodes that are neither defined in the current API of this lib nor will they ever be used by a virtual keyboard. I will change the limit (keyMax) to ensure that this issue won't affect others and create a patch release, as the API won't change from a lib user's perspective.

Cheers
Ben

P.S.: Feel free to use the new version once it's released and please let me know if any issues should persist.
